import { SVGProps } from "react";

export const AuracleBorder = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width="100%"
    height="100%"
    viewBox="0 0 400 400"
    preserveAspectRatio="xMidYMid slice"
    xmlns="http://www.w3.org/2000/svg"
  >
    {/* Large Dots (middle of the border) */}
    <circle
      cx="200"
      cy="50"
      r="12"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="150"
      cy="70"
      r="16"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="100"
      cy="100"
      r="14"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="60"
      cy="150"
      r="15"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="40"
      cy="200"
      r="13"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="60"
      cy="250"
      r="14"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="100"
      cy="300"
      r="15"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="150"
      cy="330"
      r="16"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="200"
      cy="350"
      r="14"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="250"
      cy="330"
      r="15"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="300"
      cy="300"
      r="13"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="340"
      cy="250"
      r="16"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="360"
      cy="200"
      r="14"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="340"
      cy="150"
      r="15"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="300"
      cy="100"
      r="13"
      fill="currentColor"
      className="text-primary/30"
    />
    <circle
      cx="250"
      cy="70"
      r="16"
      fill="currentColor"
      className="text-primary/30"
    />

    {/* Medium Dots (between large and small) */}
    <circle
      cx="175"
      cy="55"
      r="10"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="125"
      cy="80"
      r="9"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="80"
      cy="125"
      r="8"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="55"
      cy="175"
      r="9"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="50"
      cy="225"
      r="8"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="80"
      cy="275"
      r="9"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="125"
      cy="320"
      r="10"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="175"
      cy="345"
      r="8"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="225"
      cy="345"
      r="9"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="275"
      cy="320"
      r="8"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="320"
      cy="275"
      r="10"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="345"
      cy="225"
      r="9"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="350"
      cy="175"
      r="8"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="320"
      cy="125"
      r="9"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="275"
      cy="80"
      r="10"
      fill="currentColor"
      className="text-primary/25"
    />
    <circle
      cx="225"
      cy="55"
      r="8"
      fill="currentColor"
      className="text-primary/25"
    />

    {/* Small Dots (outer and inner edges) */}
    <circle
      cx="200"
      cy="30"
      r="4"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="160"
      cy="35"
      r="3"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="120"
      cy="50"
      r="5"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="80"
      cy="75"
      r="4"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="50"
      cy="120"
      r="3"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="35"
      cy="160"
      r="5"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="30"
      cy="200"
      r="4"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="35"
      cy="240"
      r="3"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="50"
      cy="280"
      r="5"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="75"
      cy="320"
      r="4"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="120"
      cy="350"
      r="3"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="160"
      cy="365"
      r="5"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="200"
      cy="370"
      r="4"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="240"
      cy="365"
      r="3"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="280"
      cy="350"
      r="5"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="320"
      cy="320"
      r="4"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="350"
      cy="280"
      r="3"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="365"
      cy="240"
      r="5"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="370"
      cy="200"
      r="4"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="365"
      cy="160"
      r="3"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="350"
      cy="120"
      r="5"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="320"
      cy="80"
      r="4"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="280"
      cy="50"
      r="3"
      fill="currentColor"
      className="text-primary/20"
    />
    <circle
      cx="240"
      cy="35"
      r="5"
      fill="currentColor"
      className="text-primary/20"
    />

    {/* Tiny Dots (for extra detail) */}
    <circle
      cx="195"
      cy="15"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="145"
      cy="25"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="95"
      cy="55"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="55"
      cy="95"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="25"
      cy="145"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="15"
      cy="195"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="25"
      cy="245"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="55"
      cy="295"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="95"
      cy="345"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="145"
      cy="375"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="195"
      cy="385"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="245"
      cy="375"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="295"
      cy="345"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="345"
      cy="295"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="375"
      cy="245"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="385"
      cy="195"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="375"
      cy="145"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="345"
      cy="95"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="295"
      cy="55"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />
    <circle
      cx="245"
      cy="25"
      r="2"
      fill="currentColor"
      className="text-primary/15"
    />

    {/* Create a mask to only show the border area */}
    <mask id="borderMask">
      <rect width="100%" height="100%" fill="white" />
      <rect
        x="80"
        y="80"
        width="240"
        height="240"
        fill="black"
        rx="10"
        ry="10"
      />
    </mask>

    {/* Apply the mask to all circles */}
    <rect
      width="100%"
      height="100%"
      fill="transparent"
      mask="url(#borderMask)"
    />
  </svg>
);
